name: Node.js CI

on:
  push:
    branches: ["final-project" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_FOLDER: automation-fop-help
      HEADLESS: true
      FOR_HELP_API_BASE_URL: ${{ secrets.FOR_HELP_API_BASE_URL }}
      FH_USER_NAME: ${{ secrets.FH_USER_NAME }}
      FH_PASSWORD: ${{ secrets.FH_PASSWORD }}

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: automation-fop-help/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ${{ env.BUILD_FOLDER }}
        
      - name: Run UI tests
        run: npm run test:ui:ci
        working-directory: ${{ env.BUILD_FOLDER }}
        if: always()   
        
      - name: Run API tests
        run: npm run test:api:ci
        working-directory: ${{ env.BUILD_FOLDER }}
        if: always()    
      
      - name: Run API Integration tests
        run: npm run test:api-integration:ci
        working-directory: ${{ env.BUILD_FOLDER }}
        if: always()

      - name: Merge Allure results
        run: 
          mkdir -p ${{ env.BUILD_FOLDER }}/allure-results-merged
          cp -r ${{ env.BUILD_FOLDER }}/allure-results/* ${{ env.BUILD_FOLDER }}/allure-results-merged/ || true
          cp -r ${{ env.BUILD_FOLDER }}/allure-results-api/* ${{ env.BUILD_FOLDER }}/allure-results-merged/ || true
          cp -r ${{ env.BUILD_FOLDER }}/allure-results-api-integration/* ${{ env.BUILD_FOLDER }}/allure-results-merged/ || true
        working-directory: ${{ env.BUILD_FOLDER }}
        if: always()

      - name: Build Allure report
        run: npx allure generate allure-results-merged --clean --single-file -o allure-report
        working-directory: ${{ env.BUILD_FOLDER }}
        if: always()  

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-html-report
          path: ${{ env.BUILD_FOLDER }}/allure-report
          retention-days: 30
